package net.doyouhike.app.wildbird.biz.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import net.doyouhike.app.wildbird.biz.db.bean.DbWildBird;

import net.doyouhike.app.wildbird.biz.db.bean.DbComment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMMENT".
*/
public class CommentDao extends AbstractDao<DbComment, Long> {

    public static final String TABLENAME = "COMMENT";

    /**
     * Properties of entity DbComment.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CommentID = new Property(0, Long.class, "commentID", true, "COMMENT_ID");
        public final static Property UserID = new Property(1, String.class, "userID", false, "USER_ID");
        public final static Property UserName = new Property(2, String.class, "userName", false, "USER_NAME");
        public final static Property IsLike = new Property(3, Integer.class, "isLike", false, "IS_LIKE");
        public final static Property Avatar = new Property(4, String.class, "avatar", false, "AVATAR");
        public final static Property LikeNum = new Property(5, Integer.class, "likeNum", false, "LIKE_NUM");
        public final static Property Content = new Property(6, String.class, "content", false, "CONTENT");
        public final static Property Time = new Property(7, String.class, "time", false, "TIME");
        public final static Property SpeciesID = new Property(8, String.class, "speciesID", false, "SPECIES_ID");
    };

    private WbDaoSession daoSession;

    private Query<DbComment> wildBird_CommentsQuery;

    public CommentDao(DaoConfig config) {
        super(config);
    }
    
    public CommentDao(DaoConfig config, WbDaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMMENT\" (" + //
                "\"COMMENT_ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: commentID
                "\"USER_ID\" TEXT," + // 1: userID
                "\"USER_NAME\" TEXT," + // 2: userName
                "\"IS_LIKE\" INTEGER," + // 3: isLike
                "\"AVATAR\" TEXT," + // 4: avatar
                "\"LIKE_NUM\" INTEGER," + // 5: likeNum
                "\"CONTENT\" TEXT," + // 6: content
                "\"TIME\" TEXT," + // 7: time
                "\"SPECIES_ID\" TEXT);"); // 8: speciesID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMMENT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbComment entity) {
        stmt.clearBindings();

        Long commentID = entity.getCommentID();
        if (commentID != null) {
            stmt.bindLong(1, commentID);
        }
 
        String userID = entity.getUserID();
        if (userID != null) {
            stmt.bindString(2, userID);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(3, userName);
        }
 
        Integer isLike = entity.getIsLike();
        if (isLike != null) {
            stmt.bindLong(4, isLike);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(5, avatar);
        }
 
        Integer likeNum = entity.getLikeNum();
        if (likeNum != null) {
            stmt.bindLong(6, likeNum);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(7, content);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(8, time);
        }
 
        String speciesID = entity.getSpeciesID();
        if (speciesID != null) {
            stmt.bindString(9, speciesID);
        }
    }

    @Override
    protected void attachEntity(DbComment entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbComment readEntity(Cursor cursor, int offset) {
        DbComment entity = new DbComment( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // commentID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userName
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // isLike
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // avatar
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // likeNum
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // content
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // time
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // speciesID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbComment entity, int offset) {
        entity.setCommentID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsLike(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setAvatar(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLikeNum(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setContent(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSpeciesID(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbComment entity, long rowId) {
        return entity.getCommentID();
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbComment entity) {
        if(entity != null) {
            return entity.getCommentID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "comments" to-many relationship of DbWildBird. */
    public List<DbComment> _queryWildBird_Comments(String speciesID) {
        synchronized (this) {
            if (wildBird_CommentsQuery == null) {
                QueryBuilder<DbComment> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SpeciesID.eq(null));
                wildBird_CommentsQuery = queryBuilder.build();
            }
        }
        Query<DbComment> query = wildBird_CommentsQuery.forCurrentThread();
        query.setParameter(0, speciesID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWildBirdDao().getAllColumns());
            builder.append(" FROM COMMENT T");
            builder.append(" LEFT JOIN WILD_BIRD T0 ON T.\"SPECIES_ID\"=T0.\"SPECIES_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbComment loadCurrentDeep(Cursor cursor, boolean lock) {
        DbComment entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbWildBird wildBird = loadCurrentOther(daoSession.getWildBirdDao(), cursor, offset);
        entity.setWildBird(wildBird);

        return entity;    
    }

    public DbComment loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbComment> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbComment> list = new ArrayList<DbComment>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbComment> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbComment> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
