package net.doyouhike.app.wildbird.biz.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import net.doyouhike.app.wildbird.biz.db.bean.DbWildBird;

import net.doyouhike.app.wildbird.biz.db.bean.DbImage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE".
*/
public class ImageDao extends AbstractDao<DbImage, Long> {

    public static final String TABLENAME = "IMAGE";

    /**
     * Properties of entity DbImage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property Author = new Property(2, String.class, "author", false, "AUTHOR");
        public final static Property SpeciesID = new Property(3, String.class, "speciesID", false, "SPECIES_ID");
    };

    private WbDaoSession daoSession;

    private Query<DbImage> wildBird_ImagesQuery;

    public ImageDao(DaoConfig config) {
        super(config);
    }
    
    public ImageDao(DaoConfig config, WbDaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT,"+
                "\"URL\" TEXT," + // 0: url
                "\"AUTHOR\" TEXT," + // 1: author
                "\"SPECIES_ID\" TEXT);"); // 2: speciesID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbImage entity) {
        stmt.clearBindings();

        Long id=entity.getId();
        if (null!=id){
            stmt.bindLong(1, id);
        }

        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
 
        String speciesID = entity.getSpeciesID();
        if (speciesID != null) {
            stmt.bindString(4, speciesID);
        }
    }

    @Override
    protected void attachEntity(DbImage entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbImage readEntity(Cursor cursor, int offset) {
        DbImage entity = new DbImage( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // author
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // speciesID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbImage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAuthor(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSpeciesID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbImage entity, long rowId) {
        // Unsupported or missing PK type
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbImage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "images" to-many relationship of DbWildBird. */
    public List<DbImage> _queryWildBird_Images(String speciesID) {
        synchronized (this) {
            if (wildBird_ImagesQuery == null) {
                QueryBuilder<DbImage> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SpeciesID.eq(null));
                wildBird_ImagesQuery = queryBuilder.build();
            }
        }
        Query<DbImage> query = wildBird_ImagesQuery.forCurrentThread();
        query.setParameter(0, speciesID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWildBirdDao().getAllColumns());
            builder.append(" FROM IMAGE T");
            builder.append(" LEFT JOIN WILD_BIRD T0 ON T.\"SPECIES_ID\"=T0.\"SPECIES_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbImage loadCurrentDeep(Cursor cursor, boolean lock) {
        DbImage entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbWildBird wildBird = loadCurrentOther(daoSession.getWildBirdDao(), cursor, offset);
        entity.setWildBird(wildBird);

        return entity;    
    }

    public DbImage loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbImage> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbImage> list = new ArrayList<DbImage>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbImage> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbImage> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
